spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/db_syzx?characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB