package cn.ncist.glx.expcenter.beans.po;

import java.util.Date;

public class ApplyExperiment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_experiment.id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_experiment.apply_time
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private Date applyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_experiment.status
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_experiment.course_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_experiment.experiment_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private Integer experimentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_experiment.type
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_experiment.desc
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_experiment.change_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private Integer changeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_experiment.id
     *
     * @return the value of apply_experiment.id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_experiment.id
     *
     * @param id the value for apply_experiment.id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_experiment.apply_time
     *
     * @return the value of apply_experiment.apply_time
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_experiment.apply_time
     *
     * @param applyTime the value for apply_experiment.apply_time
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_experiment.status
     *
     * @return the value of apply_experiment.status
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_experiment.status
     *
     * @param status the value for apply_experiment.status
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_experiment.course_id
     *
     * @return the value of apply_experiment.course_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_experiment.course_id
     *
     * @param courseId the value for apply_experiment.course_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_experiment.experiment_id
     *
     * @return the value of apply_experiment.experiment_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public Integer getExperimentId() {
        return experimentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_experiment.experiment_id
     *
     * @param experimentId the value for apply_experiment.experiment_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setExperimentId(Integer experimentId) {
        this.experimentId = experimentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_experiment.type
     *
     * @return the value of apply_experiment.type
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_experiment.type
     *
     * @param type the value for apply_experiment.type
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_experiment.desc
     *
     * @return the value of apply_experiment.desc
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_experiment.desc
     *
     * @param desc the value for apply_experiment.desc
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_experiment.change_id
     *
     * @return the value of apply_experiment.change_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public Integer getChangeId() {
        return changeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_experiment.change_id
     *
     * @param changeId the value for apply_experiment.change_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setChangeId(Integer changeId) {
        this.changeId = changeId;
    }
}