package cn.ncist.glx.expcenter.beans.po;

import java.util.Date;

public class ChangeExperiment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_experiment.id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_experiment.expriment_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private Integer exprimentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_experiment.after_name
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private String afterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_experiment.after_desc
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private String afterDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_experiment.after_room_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private Integer afterRoomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_experiment.after_datetime
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private Date afterDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_experiment.after_number
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private Integer afterNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_experiment.id
     *
     * @return the value of change_experiment.id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_experiment.id
     *
     * @param id the value for change_experiment.id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_experiment.expriment_id
     *
     * @return the value of change_experiment.expriment_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public Integer getExprimentId() {
        return exprimentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_experiment.expriment_id
     *
     * @param exprimentId the value for change_experiment.expriment_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setExprimentId(Integer exprimentId) {
        this.exprimentId = exprimentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_experiment.after_name
     *
     * @return the value of change_experiment.after_name
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public String getAfterName() {
        return afterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_experiment.after_name
     *
     * @param afterName the value for change_experiment.after_name
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setAfterName(String afterName) {
        this.afterName = afterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_experiment.after_desc
     *
     * @return the value of change_experiment.after_desc
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public String getAfterDesc() {
        return afterDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_experiment.after_desc
     *
     * @param afterDesc the value for change_experiment.after_desc
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setAfterDesc(String afterDesc) {
        this.afterDesc = afterDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_experiment.after_room_id
     *
     * @return the value of change_experiment.after_room_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public Integer getAfterRoomId() {
        return afterRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_experiment.after_room_id
     *
     * @param afterRoomId the value for change_experiment.after_room_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setAfterRoomId(Integer afterRoomId) {
        this.afterRoomId = afterRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_experiment.after_datetime
     *
     * @return the value of change_experiment.after_datetime
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public Date getAfterDatetime() {
        return afterDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_experiment.after_datetime
     *
     * @param afterDatetime the value for change_experiment.after_datetime
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setAfterDatetime(Date afterDatetime) {
        this.afterDatetime = afterDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_experiment.after_number
     *
     * @return the value of change_experiment.after_number
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public Integer getAfterNumber() {
        return afterNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_experiment.after_number
     *
     * @param afterNumber the value for change_experiment.after_number
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setAfterNumber(Integer afterNumber) {
        this.afterNumber = afterNumber;
    }
}