package cn.ncist.glx.expcenter.beans.po;

public class ChangeCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_course.id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_course.course_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_course.after_name
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private String afterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_course.after_classs_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private String afterClasssId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_course.after_people
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private String afterPeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column change_course.after_counts
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private String afterCounts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_course.id
     *
     * @return the value of change_course.id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_course.id
     *
     * @param id the value for change_course.id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_course.course_id
     *
     * @return the value of change_course.course_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_course.course_id
     *
     * @param courseId the value for change_course.course_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_course.after_name
     *
     * @return the value of change_course.after_name
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public String getAfterName() {
        return afterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_course.after_name
     *
     * @param afterName the value for change_course.after_name
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setAfterName(String afterName) {
        this.afterName = afterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_course.after_classs_id
     *
     * @return the value of change_course.after_classs_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public String getAfterClasssId() {
        return afterClasssId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_course.after_classs_id
     *
     * @param afterClasssId the value for change_course.after_classs_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setAfterClasssId(String afterClasssId) {
        this.afterClasssId = afterClasssId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_course.after_people
     *
     * @return the value of change_course.after_people
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public String getAfterPeople() {
        return afterPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_course.after_people
     *
     * @param afterPeople the value for change_course.after_people
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setAfterPeople(String afterPeople) {
        this.afterPeople = afterPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column change_course.after_counts
     *
     * @return the value of change_course.after_counts
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public String getAfterCounts() {
        return afterCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column change_course.after_counts
     *
     * @param afterCounts the value for change_course.after_counts
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setAfterCounts(String afterCounts) {
        this.afterCounts = afterCounts;
    }
}