package cn.ncist.glx.expcenter.beans.po;

public class Club {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.username
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.password
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.nickname
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.leader
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private String leader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.tel
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.classes
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private String classes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club.desc
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.id
     *
     * @return the value of club.id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.id
     *
     * @param id the value for club.id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.username
     *
     * @return the value of club.username
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.username
     *
     * @param username the value for club.username
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.password
     *
     * @return the value of club.password
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.password
     *
     * @param password the value for club.password
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.nickname
     *
     * @return the value of club.nickname
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.nickname
     *
     * @param nickname the value for club.nickname
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.leader
     *
     * @return the value of club.leader
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.leader
     *
     * @param leader the value for club.leader
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setLeader(String leader) {
        this.leader = leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.tel
     *
     * @return the value of club.tel
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.tel
     *
     * @param tel the value for club.tel
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.classes
     *
     * @return the value of club.classes
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public String getClasses() {
        return classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.classes
     *
     * @param classes the value for club.classes
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setClasses(String classes) {
        this.classes = classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club.desc
     *
     * @return the value of club.desc
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club.desc
     *
     * @param desc the value for club.desc
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }
}