package cn.ncist.glx.expcenter.beans.po;

public class Config {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.key
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.value
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.key
     *
     * @return the value of config.key
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.key
     *
     * @param key the value for config.key
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.value
     *
     * @return the value of config.value
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.value
     *
     * @param value the value for config.value
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        return "Config{" +
                "key='" + key + '\'' +
                ", value='" + value + '\'' +
                '}';
    }
}