package cn.ncist.glx.expcenter.beans.po;

public class Platform {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.id
     *
     * @mbg.generated Sun May 09 09:41:27 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.name
     *
     * @mbg.generated Sun May 09 09:41:27 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.url
     *
     * @mbg.generated Sun May 09 09:41:27 CST 2021
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.details
     *
     * @mbg.generated Sun May 09 09:41:27 CST 2021
     */
    private String details;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.id
     *
     * @return the value of platform.id
     *
     * @mbg.generated Sun May 09 09:41:27 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.id
     *
     * @param id the value for platform.id
     *
     * @mbg.generated Sun May 09 09:41:27 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.name
     *
     * @return the value of platform.name
     *
     * @mbg.generated Sun May 09 09:41:27 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.name
     *
     * @param name the value for platform.name
     *
     * @mbg.generated Sun May 09 09:41:27 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.url
     *
     * @return the value of platform.url
     *
     * @mbg.generated Sun May 09 09:41:27 CST 2021
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.url
     *
     * @param url the value for platform.url
     *
     * @mbg.generated Sun May 09 09:41:27 CST 2021
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.details
     *
     * @return the value of platform.details
     *
     * @mbg.generated Sun May 09 09:41:27 CST 2021
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.details
     *
     * @param details the value for platform.details
     *
     * @mbg.generated Sun May 09 09:41:27 CST 2021
     */
    public void setDetails(String details) {
        this.details = details;
    }
}