package cn.ncist.glx.expcenter.beans.po;

public class Refuse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refuse.id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refuse.apply_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private Integer applyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refuse.type
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refuse.reason
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    private String reason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refuse.id
     *
     * @return the value of refuse.id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refuse.id
     *
     * @param id the value for refuse.id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refuse.apply_id
     *
     * @return the value of refuse.apply_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public Integer getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refuse.apply_id
     *
     * @param applyId the value for refuse.apply_id
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setApplyId(Integer applyId) {
        this.applyId = applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refuse.type
     *
     * @return the value of refuse.type
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refuse.type
     *
     * @param type the value for refuse.type
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refuse.reason
     *
     * @return the value of refuse.reason
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refuse.reason
     *
     * @param reason the value for refuse.reason
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    public void setReason(String reason) {
        this.reason = reason;
    }
}