package cn.ncist.glx.expcenter.home.mapper;

import cn.ncist.glx.expcenter.beans.po.ApplyExperiment;
import java.util.List;

public interface ApplyExperimentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_experiment
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_experiment
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int insert(ApplyExperiment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_experiment
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    ApplyExperiment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_experiment
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    List<ApplyExperiment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_experiment
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int updateByPrimaryKey(ApplyExperiment record);
}