package cn.ncist.glx.expcenter.home.mapper;

import cn.ncist.glx.expcenter.beans.po.ApplyActivity;
import java.util.List;

public interface ApplyActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_activity
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_activity
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int insert(ApplyActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_activity
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    ApplyActivity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_activity
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    List<ApplyActivity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_activity
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int updateByPrimaryKey(ApplyActivity record);
}