package cn.ncist.glx.expcenter.home.mapper;

import cn.ncist.glx.expcenter.beans.po.Refuse;
import java.util.List;

public interface RefuseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refuse
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refuse
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int insert(Refuse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refuse
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    Refuse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refuse
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    List<Refuse> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refuse
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int updateByPrimaryKey(Refuse record);
}