package cn.ncist.glx.expcenter.manage.mapper;

import cn.ncist.glx.expcenter.beans.po.ChangeExperiment;

import java.util.List;

public interface ChangeExperimentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_experiment
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_experiment
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int insert(ChangeExperiment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_experiment
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    ChangeExperiment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_experiment
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    List<ChangeExperiment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_experiment
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int updateByPrimaryKey(ChangeExperiment record);
}