package cn.ncist.glx.expcenter.manage.mapper;

import cn.ncist.glx.expcenter.beans.po.ChangeCourse;

import java.util.List;

public interface ChangeCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_course
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_course
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int insert(ChangeCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_course
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    ChangeCourse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_course
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    List<ChangeCourse> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_course
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int updateByPrimaryKey(ChangeCourse record);
}