package cn.ncist.glx.expcenter.manage.mapper;

import cn.ncist.glx.expcenter.beans.po.Club;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ClubMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int insert(Club record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    Club selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    List<Club> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int updateByPrimaryKey(Club record);

    Club login(@Param("username") String username,@Param("password") String password);
}