package cn.ncist.glx.expcenter.manage.mapper;

import cn.ncist.glx.expcenter.beans.po.Config;

import java.util.List;

public interface ConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int deleteByPrimaryKey(String key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int insert(Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    Config selectByPrimaryKey(String key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    List<Config> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int updateByPrimaryKey(Config record);

}