package cn.ncist.glx.expcenter.manage.mapper;

import cn.ncist.glx.expcenter.beans.po.Experiment;

import java.util.List;

public interface ExperimentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experiment
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experiment
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int insert(Experiment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experiment
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    Experiment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experiment
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    List<Experiment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experiment
     *
     * @mbg.generated Thu Apr 29 17:13:43 CST 2021
     */
    int updateByPrimaryKey(Experiment record);

    void delByCourseId(Integer courseId);

    List<Experiment> selectByCourseId(int courseId);

    int getRoomCount(Integer id);
}