package cn.ncist.glx.expcenter.manage.mapper;

import cn.ncist.glx.expcenter.beans.po.Platform;

import java.util.List;

public interface PlatformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform
     *
     * @mbg.generated Sun May 09 09:41:27 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform
     *
     * @mbg.generated Sun May 09 09:41:27 CST 2021
     */
    int insert(Platform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform
     *
     * @mbg.generated Sun May 09 09:41:27 CST 2021
     */
    Platform selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform
     *
     * @mbg.generated Sun May 09 09:41:27 CST 2021
     */
    List<Platform> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform
     *
     * @mbg.generated Sun May 09 09:41:27 CST 2021
     */
    int updateByPrimaryKey(Platform record);
}